---
# yamllint configuration customization file
## Configuration file customization reference:
## https://yamllint.readthedocs.io/en/stable/configuration.html

# Extend the default yamllint configuration
extends: default

rules:
  # Allow an empty space within braces
  braces:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: 1
  # Allow an empty space within brackets
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: 1
  # Require comment indentation to match like content
  comments-indentation: enable
  # Require the use of the document start marker (---)
  document-start:
    level: warning
    present: true
  # Disallow the use of trailing spaces
  trailing-spaces: enable
  # Allow the use of 'on' in GitHub Actions
  truthy:
    # Allow use of the "on" key label for GitHub Actions workflows
    check-keys: false
    level: warning
