---
# Build Documentation with MkDocs
name: Build Documentation With MkDocs

# Set the GitHub event triggers
on:
  # Trigger the workflow on push events for the main branch
  push:
    branches:
      - main

  # Allows manual run of the Action
  workflow_dispatch:

# Set environment variables
env:
  CONFIG_FILE: mkdocs.insiders.yml
  GIT_PREFIX: 'git+https://'
  GIT_SUFFIX: '@github.com/timothyhull/mkdocs-material-insiders.git'
  MKDOCS_TOKEN: ${{ secrets.MKDOCS_TOKEN }}

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # checkout@ action documentation
      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: recursive
          # "fetch-depth 0" pulls the latest commit date for each file
          # This allows support for publishing the latest revision date
          fetch-depth: 0

      # setup-python@ action documentation
      # https://github.com/marketplace/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # cache@ action documentation
      # https://github.com/actions/cache
      - name: Set build cache version
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install Material for MkDocs Insiders
        run: |
          python -m pip install \
          ${{ env.GIT_PREFIX }}${{ env.MKDOCS_TOKEN }}${{ env.GIT_SUFFIX }}

      - name: Deploy
        run: |
          mkdocs gh-deploy --config-file ${{ env.CONFIG_FILE }} --force
